### PR TITLE
Custom format and custom year range for date picker fields

### PR DESCRIPTION
**Pull request by felipeelia**
As the default format (yy-mm-dd) is really bad for non-english users I've had this idea of creating two additional fields just for date pickers. This way the real date field is hidden (and continues with the yyyy-mm-dd format)  but a fake one is shown with the desired format (using altField/altFormat datepicker ui options).
This PR also solves the #41 problem, letting the user define what range to show.

I've tested it a little bit here and for me works as expected. I really hope this helps you guys to improve the plugin :)

As English is not my first language feel free to correct any grammar mistakes.

### CODE REVIEW

**Comment by Mashenka** [comment]
@EliaBR WP-CRM takes a date and time format from General site settings, doesn't that solve your issue?

**Comment by felipeelia** [comment]
Not sure if we're talking about the same issue @Mashenka. For datepicker input fields, wp-crm only gets dates on yyyy-mm-dd format for me. Did I miss something?

**Comment by Mashenka** [comment]
@EliaBR did you try to change date format here - https://www.screencast.com/t/pPy01QFcL
I think that should take format from there. If not, need to create an issue for that. Do you think that will be a better solution than yours?

**Comment by felipeelia** [comment]
Yes, I tried @Mashenka :( 
Take a look at the "Data de nascimento" field [here](http://www.eudigox.com.br/cadastro/) for example. In this page we are loading `datepicker-pt-BR.js`, and that sets the default dateFormat as `dateFormat: 'dd/mm/yy'`, but the `wp-crm/static/scripts/wp_crm_profile_editor.js` sets ` dateFormat: "yy-mm-dd"` when calling datepicker construction method. The PR sets a HTML attribute on a fake field showing it with the desired format but at the same time preserving the format we need to save it into DB.
I really don't know if there is a better solution than mine... For the range problem I think it's very good, because in birthday fields, for instance, we need a great number of years but only the past ones. For the format problem it helps at least, but it could evolve to using "date and time format from General site settings" as you said, or a new general config on WP-CRM config page, but I think there are some cases where we use different fields formats, when we don't need the year, for instance.

**Comment by Mashenka** [comment]
Thank you for your contribution, we will check your code and let you know.

**Comment by Mashenka** [comment]
@EliaBR we accepting pull requests to latest branch, not to this one. Please check the conflict and do pull request to another branch

**Comment by felipeelia** [comment]
Hi @Mashenka,

Sure I can redo the code, but you people really do want that solution that way? It was mergeble a month ago when I did this PR, just don't wanna make some effort if you just want to solve the problem in another way or even if you think these dates fields aren't a problem at all.

**Comment by Mashenka** [comment]
Actually, you are right, the best solution is to take date format from general settings of the site. You could do that and we will check.

I have also created that improvement as task on our raodmap - https://github.com/wp-crm/wp-crm/issues/130

**Pull request closed without merging**
