### PR TITLE
Redirect url in form settings and shortcode.

### PR DESCRIPTION
**Pull request by alimuzzaman**
User will be able to set redirectt url on form settings and shortcode( redirect_url );

### CODE REVIEW

**Comment by Mashenka** [comment]
@alimuzzaman 
image

image

**Comment by alimuzzaman** [comment]
@Mashenka you need to add http/https.

**Comment by Mashenka** [comment]
@alimuzzaman can you also add here with an explanation about http or //
image

**Comment by alimuzzaman** [comment]
@Mashenka https://en.wikipedia.org/wiki/Wikipedia:Protocol-relative_URL

**Comment by Mashenka** [comment]
@alimuzzaman I meant add info about new parameter in shortcode

**Comment by alimuzzaman** [comment]
Ok

**Pull request merged**
